import { roboto_mono } from '@/configs/font'
import { MainLayout } from '@/layout'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Next.js + Jotai + Tailwind CSS',
  description: 'Generated by Next.js + Jotai + Tailwind CSS',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.variable}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
