import type { Metadata } from "next";
import "./globals.css";
import { roboto_mono } from "@/configs/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.variable}>{children}</body>
    </html>
  );
}
